### PR TITLE
Use tibble package, but keep tbl_df() here

### PR DESCRIPTION
**Pull request by krlmlr**
Same as #1595, but tbl_df() remains in dplyr. Documentation of tbl_df() still needs to be adapted.

Closes #1595.

### CODE REVIEW

**Comment by krlmlr** [comment]
Should work with https://github.com/hadley/tibble/pull/57.

Compare #1595 and #1737 locally:

```
git remote add krlmlr https://github.com/krlmlr/dplyr.git
git fetch krlmlr
git diff krlmlr/tibble-2 krlmlr/tibble-3
```

GitHub compare currently doesn't work here, branches are unrelated.

See 211c10c for documentation update.

**Comment by hadley** [comment]
This should work with release tibble too, right?

**Comment by krlmlr** [comment]
Yes; only if both are attached, there'll be warnings.

**Comment by hadley** [comment]
Ah, that's true.  I think that's ok - unless you have any objections, I'll merge this PR, and by the time dplyr is on CRAN, we'll have had another tibble release.

**Comment by krlmlr** [comment]
Fine with me.

**Comment by krlmlr** [comment]
I'll just add another commit that removes a check warning.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
