### PR TITLE
Update documentation for na_if

### PR DESCRIPTION
**Pull request by pkq**
Replace the incomplete description of the second argument for na_if. Other files were automatically modified by Roxygen 5.0.1.

### CODE REVIEW

**Comment by krlmlr** [comment]
Would you mind re-creating documentation with the current dev version of roxygen2?

**Comment by pkq** [comment]
Sure thing. Note that when I do so, roxygen2 updates the alias order for many other functions, as per https://github.com/klutometis/roxygen/commit/c2cb3ef. I've split it into two commits (one for updates to alias order, and one for the actual change to na_if), but if there's anything else I can do, please let me know!

**Comment by krlmlr** [comment]
@hadley: PTAL.

**Comment by hadley** [comment]
LGTM

**Comment by krlmlr** [comment]
Thanks!

**Comment by pkq** [comment]
Happy to help! Thanks for such a fantastic tool!

**Pull request merged**
