### PR TITLE
Implement as_data_frame.tbl_cube()

### PR DESCRIPTION
**Pull request by krlmlr**
as a simple wrapper of as.data.frame.tbl_cube(); converts dims to character variables.

With test.

### CODE REVIEW

**Comment by krlmlr** [comment]
Merged with master.

**Comment by hadley** [comment]
I guess this should now go in tibble?

**Comment by krlmlr** [comment]
If tbl_cube is a dplyr concept, I think this belongs here.

**Comment by hadley** [comment]
Yeah, you're right.  Would you mind squashing this?

**Comment by krlmlr** [comment]
Squashed.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
