### PR TITLE
make operator<<() definition for Rcomplex conditional on Rcpp <= 0.12.2

### PR DESCRIPTION
**Pull request by eddelbuettel**
passes R CMD check with both Rcpp 0.12.1 and 0.12.2

### CODE REVIEW

**Comment by hadley** [comment]
Sorry it's taken me so long to get to this. Is it still necessary?

**Comment by eddelbuettel** [comment]
Cute.  A bug report from five month ago.

**Comment by hadley** [comment]
Thanks!

**Comment by eddelbuettel** [comment]
My pleasure. Glad it helped.

**Pull request merged**
