### PR TITLE
New group_names() to return group names as character vector

### PR DESCRIPTION
**Pull request by krlmlr**
in `groups()`. This is a breaking change, in preparation for #1950.

@hadley: PTAL.

### CODE REVIEW

**Comment by hadley** [comment]
Hmmmm, this is going to break every backend, and coordinating the changes is going to be hard. What if we made a new generic `group_vars()` (?) instead? It could have a default method that did `lapply(groups(x), as.character)` with a message/warning.

**Comment by hadley** [comment]
@krlmlr do you have thoughts on how your API diffing package might handle this? It seems like you'd need some manual tags to flag changes in data types.

**Comment by krlmlr** [comment]
@hadley: Added group_vars() generic instead, also using it internally. Could you please also look at #2382?

**Comment by krlmlr** [comment]
Added tests. @hadley: PTAL.

**Pull request merged**
