### PR TITLE
Rewrite min and max hybrid handlers

### LINKED ISSUE #2305: Hybrid version of max(NA_real_, na.rm = TRUE) returns NA
```r
data_frame(a = NA_real_) %>% summarise(a = max(a, na.rm = TRUE))
## # A tibble: 1 × 1
##       a
##   <dbl>
## 1    NA
```

### PR DESCRIPTION
**Pull request by krlmlr**
Now handled by a single template class, with support for all corner cases (empty vector, NA values, ...). For integer input, `NA` is returned instead of `Inf`.

Fixes #2305.

@hadley: PTAL.

### CODE REVIEW

**Comment by hadley** [comment]
How hard would it be expose this directly as an R function? I'd be interested in a benchmark vs base R and the previous version. 

Maybe having four templated alternatives (missing yes/no + int/double) would be faster and lead to simple code (albeit with a small amount of duplicated code)

**Comment by krlmlr** [comment]
It's already there: `with_hybrid(max(a), a = 1:5)` vs. `without_hybrid((max)(a), a = 1:5)`. (Just fixed a few problems in master.)

## Current master

``` r
library(dplyr, warn.conflicts = FALSE)
N <- 1e7
x <- runif(N)
xx <- x
xx[N/2] <- NA

microbenchmark::microbenchmark(
  dplyr:::with_hybrid(max(x), x),
  dplyr:::without_hybrid((max)(x), x),
  dplyr:::with_hybrid(max(x, na.rm = TRUE), x),
  dplyr:::without_hybrid((max)(x, na.rm = TRUE), x),
  times = 20
)
#> Unit: milliseconds
#>                                               expr      min       lq
#>                     dplyr:::with_hybrid(max(x), x) 55.14655 55.65483
#>                dplyr:::without_hybrid((max)(x), x) 13.73558 14.04404
#>       dplyr:::with_hybrid(max(x, na.rm = TRUE), x) 55.05419 55.68407
#>  dplyr:::without_hybrid((max)(x, na.rm = TRUE), x) 13.48640 13.88385
#>      mean   median       uq      max neval cld
#>  57.78299 56.72489 59.26558 64.88293    20   b
#>  14.80859 14.16043 14.80196 23.42316    20  a 
#>  58.49981 56.25381 59.57602 73.41693    20   b
#>  14.32813 14.00952 14.37358 17.76009    20  a
```

## This PR

``` r
#> Unit: milliseconds
#>                                               expr      min       lq
#>                     dplyr:::with_hybrid(max(x), x) 60.99932 62.36870
#>                dplyr:::without_hybrid((max)(x), x) 13.60645 14.00775
#>       dplyr:::with_hybrid(max(x, na.rm = TRUE), x) 55.21039 55.84697
#>  dplyr:::without_hybrid((max)(x, na.rm = TRUE), x) 13.65285 14.29137
#>      mean   median       uq      max neval cld
#>  66.16124 64.89561 69.02802 75.90574    20   c
#>  15.79797 15.29058 17.63915 18.72142    20 a  
#>  58.31746 56.99891 58.81414 75.32671    20  b 
#>  15.89408 15.05983 16.87834 27.06653    20 a
```

The `na.rm` case has become a tad slower with this change (with `gcc -O2` on my laptop), overall our implementation is slower than base R's by a factor of ~3-4.

I combined the four classes into one to reduce maintenance effort (now and in the future). I'd argue that a minimal run time improvement isn't worth the extra maintenance effort, given that we're already sub-par. I could look at a profiler run if it's important, though.

**Comment by hadley** [comment]
If the hybrid is so much slower, why do we even have it?

**Comment by krlmlr** [comment]
It's faster in a grouped query, because we avoid the roundtrip to the R interpreter and the materialization of the groupwise column values.

**Comment by hadley** [comment]
Base R is pretty inconsistent:

``` r
typeof(median(FALSE))
#> [1] "logical"
typeof(median(c(FALSE, TRUE)))
#> [1] "double"

typeof(median(1L))
#> [1] "integer"
typeof(median(c(1L, 2L)))
#> [1] "double"
```

I think we should say that the hybrid median _always_ returns a double.

**Comment by krlmlr** [comment]
This PR only touches hybrid min and max.

**Comment by hadley** [comment]
Oops. The equivalent base R code is this:

``` r
typeof(min(1L, na.rm = TRUE))
#> [1] "integer"
typeof(min(NA_integer_, na.rm = TRUE))
#> Warning in min(NA_integer_, na.rm = TRUE): no non-missing arguments to min;
#> returning Inf
#> [1] "double"

typeof(min(TRUE, na.rm = TRUE))
#> [1] "integer"
typeof(min(NA, na.rm = TRUE))
#> Warning in min(NA, na.rm = TRUE): no non-missing arguments to min;
#> returning Inf
#> [1] "double"
```

Seems like it would be more consistent to always return a numeric.

**Comment by krlmlr** [comment]
Now always returning numeric. New times:

``` r
#> Unit: milliseconds
#>                                                 expr      min       lq
#>                       dplyr:::with_hybrid(max(x), x) 57.92209 58.49885
#>                  dplyr:::without_hybrid((max)(x), x) 13.72525 13.98664
#>                     dplyr:::with_hybrid(max(xx), xx) 29.64903 30.68764
#>                dplyr:::without_hybrid((max)(xx), xx) 13.82268 14.15346
#>       dplyr:::with_hybrid(max(xx, na.rm = TRUE), xx) 55.57600 55.79007
#>  dplyr:::without_hybrid((max)(xx, na.rm = TRUE), xx) 13.72621 14.23667
#>      mean   median       uq      max neval  cld
#>  60.72233 59.46146 62.08578 67.16394    20    d
#>  14.77884 14.19997 14.55969 22.61328    20 a   
#>  33.49701 32.23387 33.76267 60.47334    20  b  
#>  15.08331 14.86969 15.44266 18.15982    20 a   
#>  57.59341 56.32895 58.95452 63.45070    20   c 
#>  14.88210 14.83992 15.22170 17.00810    20 a
```

**Pull request merged**
