### PR TITLE
Add tribble to imported objects

### PR DESCRIPTION
**Pull request by chrMongeau**
The `tibble` package states that "frame_data() is an older name for tribble(). It will eventually be phased out." (See: https://github.com/tidyverse/tibble/blob/2ba09826536ec33f4fb7b2edde146f19c99d95bd/man/tribble.Rd#L25-L26 ) This commit adds `tribble` to the imported objects from `tibble`.

### CODE REVIEW

**Comment by krlmlr** [comment]
@hadley: Exporting tribble() looks sensible to me. OK?

**Comment by hadley** [comment]
LGTM

**Comment by krlmlr** [comment]
@chrMongeau: Thanks. Could you please

- [ ] run devtools::document() with the latest development version of roxygen2 installed
- [ ] add a bullet to NEWS

**Comment by chrMongeau** [comment]
@krlmlr: Of course, thank you. `devtools::document()` was done and a notice to NEWS.md was added.

**Comment by krlmlr** [comment]
Thanks. I've updated my local roxygen2 version and ran document() myself to get rid of the many empty-line changes. Could you please rebase and force-push, and also include the issue number and your GitHub handle in the NEWS entry?

**Comment by chrMongeau** [comment]
@krlmlr: Done. Added note, rebased and force-pushed.

**Comment by krlmlr** [comment]
Thanks. Closed in 7bb56529.

**Pull request closed without merging**
