### PR TITLE
add mechanism for explicit recycling of columns (#1093)

### PR DESCRIPTION
**Pull request by kevinushey**
This PR adds `recycle_each`, and `recycle_whole`, as wrappers over their corresponding `rep` counterparts. A bit of non-standard evaluation sugar is used in `data_frame` to fill in the output length based on the actual resulting number of rows.

The net result is that things like this work:

    data_frame(x = 1:10, y = recycle_each(1:2), z = recycle_whole(c('a', 'b')))

One limitation is that recycled vectors cannot depend on non-recycled vectors, and vice versa. This is a bit of a 'chicken and egg' problem -- in order to recycle a vector, we need to know the number of rows. To figure that out, we need to evaluate every non-recycled vector in the `data_frame` call. And so that evaluation can't depend on evaluation of a `recycle` vector.

### CODE REVIEW

**Comment by romainfrancois** [comment]
@kevinushey It probably would pass on travis if you merge in changes from the master branch.

**Comment by kevinushey** [comment]
Looks good now. What do you think, @hadley?

**Comment by hadley** [comment]
Hmmmmmmmm, I'd prefer an implementation that didn't need NSE, but I'm not sure I'm in love with the whole idea, given the chicken and egg problem.

**Comment by hadley** [comment]
I'm going to close for now. But I'll keep thinking about the problem.

**Pull request closed without merging**
