### PR TITLE
Early exit in case_when

### PR DESCRIPTION
**Pull request by jrnold**
If all observations have been replaced, then stop the for loop.

### CODE REVIEW

**Comment by krlmlr** [comment]
This might take longer in some cases. @hadley: Are we rewriting `case_when()` in C++ eventually?

**Comment by jrnold** [comment]
Yeah, I was thinking about that, since it has to check each time. And presumably in most cases someone is using a `case_when` function they have an expectation that all cases are at least likely to occur. I should have checked it across a variety of sizes and configurations, but I wanted to see what your thoughts were.

**Comment by hadley** [comment]
@krlmlr Yeah, that's the plan, so I'd prefer to leave optimisations until we do that.

@jrnold Sorry I couldn't merge your PR. I really appreciate the effort 😁

**Comment by jrnold** [comment]
It was a "generous" three lines, so I wouldn't say it's effort :-)

**Pull request closed without merging**
