### PR TITLE
test for mutate-if w/ single column

### PR DESCRIPTION
**Pull request by wibeasley**
#2114, #2462

### CODE REVIEW

**Comment by hadley** [comment]
This would be more compelling if it actually failed.

**Comment by wibeasley** [comment]
> This would be more compelling if it actually failed.

Sorry.  I referenced the reason in https://github.com/hadley/dplyr/issues/2462#issuecomment-281835027, and it would probably make sense to give context here.

I added it to the suite for two reasons:
1. It verifies that this basic dplyr scenario currently passes, and therefore adds value for the sake of regression testing.
1. Its passing state here contrasts with the environment in which #2462 fails.  I am guessing this highlights the unexpectedly different behavior with *vs* without the dplyr package being attached.

**Comment by hadley** [comment]
Unfortunately this doesn't really seem useful to me. I'm in a big push for dplyr right now, so I recommend reopening in a couple of months when I don't have so much on my plate.

**Comment by wibeasley** [comment]
Ok.  Thanks for your time and all the wonderful packages.

**Pull request closed without merging**
