### PR TITLE
WIP: Simplify hybrid evaluation

### LINKED ISSUE #912: Hybrid evaluation of [ fails
e.g.

``` R
library("dplyr")
library("nycflights13") 
flights %>% mutate(airport = airports[, "name"]) 
# Error: not compatible with STRSXP 
```

### LINKED ISSUE #1012: Build variable interpolation into hybrid evaluator
I see a lot of code that does something like this: 

```
f <- function(data, variable, value ){
   filter_( data, interp( ~ var == value, var = as.name(variable) ) )
}
f( iris, "Species", "setosa" )
```

which I find kind of verbose and perhaps not so easy to read. 

I was thinking of something like this: 

```
filter( data, column(variable) == value )
```

`column` would take a string like `"Species"` and substitute it to the associated name, i.e. `Species` so that eventually it is just like we were doing `filter(data, Species == value )`. 

I think it would be fairly easy to do internally, and the code would be IMO much more readable. @hadley what do you think ?

### LINKED ISSUE #1400: Better $ hybrid support
It would be nice if this worked:

``` R
library(boot)
library(dplyr)

df <- bind_rows(
  data_frame(t=1:10, ts="A", dat=1:10),
  data_frame(t=1:10, ts="B", dat=101:110)
)

bsdf <- group_by(df, ts) %>% 
  do(bs = boot(.$dat, R = 10, statistic = function(d, ind) mean(d[ind])))

bsdf %>% mutate(
  mean = bs$t0, # ok 
  var = var(bs$t) # fails
)
```

(which I'm pretty sure is because hybrid $ isn't quite right)

@romainfrancois can you take a look? If you point me to the hybrid implementation of `$` I can also think about improvements.

### LINKED ISSUE #1452: Unclear limitations on the calculations that can be performed in mutate.
I’d like to use `mutate` to create a new column but the calculations are not entirely trivial.  Here is one example illustrating the kind of things I would like to do:

``` R
d %>%
  group_by(tid) %>%
  mutate(before.event = {
    idx <- which(diff(chars) < 0)[1]
     c(rep(T, idx), rep(F, n()-idx))
  })
```

This code produces an error message saying that assignments are forbidden.  So I tried the following work-around:

``` R

f <- function(x) {
  idx <- which(diff(x) < 0)[1]
  c(rep(T, idx), rep(F, n()-idx))
}

d %>%
  group_by(tid) %>%
  mutate(before.event = f(chars))
```

but this also produces an error message:

```
Error: This function should not be called directly
```

This is fairly surprising because I can of course use other functions in mutate, e.g:

``` R
d %>%
  group_by(tid) %>%
  mutate(test = min(chars))
```

I looked in various places for an explanation but couldn’t find one (man pages, GitHub page, introduction to dplyr, …).  There clearly seem to be limitations as to which things can be done and which functions can be used but it is not clear what these limitations are.  This can be of course be a little discouraging for new users.  So I’d say there is at least a documentation issue here.

While this issue could be addressed by improving the documentation, it would of course be much better if there weren’t any limitations in the first place.  I can think of many situations where it would be extremely useful if assignments and user-defined functions were allowed.  I really like dplyr's interface but the ability to use arbitrary code-blocks to carry out calculations in conjunction with `mutate` but also `summarise` would clearly set dplyr apart from alternative solutions like reshape and data.table.

### LINKED ISSUE #1719: Hybrid support for case_when
We should talk about how to implement this - one generic approach (that might also work for `lm()`) is to construct an environment populated with promises that evaluate to the variables in the current group. Then if you call the function in the context of that environment, it should be able to use regular evaluation to get what it needs.

### PR DESCRIPTION
**Pull request by krlmlr**
Installs an environment with an active binding for each variable in the current slice, via the new bindrcpp package. Tests are in #2186, this PR is currently missing `global()` and `column()` functionality, as well as handling of `NA` in `min()` and `max()`. (Is the hybrid evaluator still active??? **EDIT**: Yes!)

Fixes #1719.

Fixes #1400.

Fixes #1452.

~~Prepares fix for~~ Fixes #912.

Fixes #1012 ~~(but untestable because of hadley/lazyeval#78)~~.

### CODE REVIEW

**Comment by hadley** [comment]
I think we could eliminate the need for the `global()` and `column()` by binding `.env` to the `parent.frame()` and `.data` to the current slice.

**Comment by krlmlr** [comment]
If we do that, we can as well add functions that do the same, perhaps with a message/warning.

**Comment by krlmlr** [comment]
This now really needs #2143 (constant folding), will add an implementation (based on `compiler`) in a separate PR. Example:

```r
compiler::compile(quote(T), options = list(optimize = 3)) %>% eval(new.env(parent = emptyenv()))
```

**Comment by krlmlr** [comment]
Closing in favor of #2190.

**Pull request closed without merging**
