### PR TITLE
Minor cleanup after rlang changes

### PR DESCRIPTION
**Pull request by krlmlr**
Follow-up to #2488.

### CODE REVIEW

**Comment by lionel-** [comment]
Of course it's better if the whole codebase uses the same style, and the ship has sailed, but I'd recommend not indenting over namespaces. Doing so makes indentation less meaningful and the code harder to parse visually. This should be paired with closing namespaces like this: `} // namespace dplyr`.

**Comment by krlmlr** [comment]
We still can change easily, but at this point `astyle` thinks that namespaces should be indented. See helper-astyle.R.

I'm happy to revise this once the C++ code reaches a stable state; also, I'd like to pad operators with spaces with the `--pad-oper` switch.

**Comment by jimhester** [comment]
FWIW If we are going to standardise on using `astyle`, we should have a `astylerc` file we can share between projects rather than passing command line arguments.

**Comment by eddelbuettel** [comment]
I have no horse in this race ...  but don't all the cool kids use [clang-format](https://clang.llvm.org/docs/ClangFormat.html) ?

**Comment by krlmlr** [comment]
Thanks for the pointer. I don't remember why I preferred astyle at that time, maybe it was just good (and noninvasive) enough and I was familiar with it. We should consider clang-format if astyle becomes insufficient.

**Pull request merged**
