### PR TITLE
Update RStudio project settings to install tests

### PR DESCRIPTION
**Pull request by krlmlr**
for https://github.com/hadley/dtplyr/pull/24.

### CODE REVIEW

**Comment by krlmlr** [comment]
I haven't found it. Does your RStudio append --install-tests when you press Cmd + Shift + B?

**Comment by hadley** [comment]
An R option, not an RStudio option

**Comment by krlmlr** [comment]
There's the `devtools.install.args` option, but RStudio Preview 0.99.1230 doesn't use it for build + install. It's used for `devtools::install()`, but that function installs tests by default. R itself seems to look exclusively for the `--install-tests` switch: https://github.com/wch/r-source/blob/5cfd0944cb9a7554c597342c8274e556bbd5df91/src/library/tools/R/install.R#L1375.

Could RStudio just call `devtools::install()` for build + install?

**Comment by hadley** [comment]
LGTM

**Pull request merged**
