### PR TITLE
New RowwiseSlicingIndex, NaturalSlicingIndex and OffsetSlicingIndex

### PR DESCRIPTION
**Pull request by krlmlr**
- allows removing redundant code
- preparation for hybrid evaluation refactoring
- reduces allocations
- a template solution (instead of virtual functions) may give better performance, can be refactored later

@hadley: PTAL.

### CODE REVIEW

**Comment by hadley** [comment]
Seems reasonable to me. Maybe worth adding a couple of lines of comments to each class to briefly describe their role?

**Comment by krlmlr** [comment]
@hadley: Added comments (e60172b). Okay to merge?

**Comment by hadley** [comment]
LGTM

**Comment by krlmlr** [comment]
For the record: Performance did improve with this PR.

bind_rows

**Comment by krlmlr** [comment]
@lionel-: The `SlicingIndex` is an interface that allows selection of a subset of rows in the hybrid evaluator. The `NaturalSlicingIndex` selects the entire data frame; see #2311 for discussion on making the ungrouped case a special case of the grouped case for all operations.

**Pull request merged**
