### PR TITLE
Update to latest rlang API

### PR DESCRIPTION
**Pull request by lionel-**
Accounts for the changes in https://github.com/hadley/rlang/pull/59 and https://github.com/hadley/rlang/pull/64

### CODE REVIEW

**Comment by krlmlr** [comment]
Can we please pin rlang to a revision or a tag?

**Comment by lionel-** [comment]
> Can we please pin rlang to a revision or a tag?

Will this work with AppVeyor? I'm updating the rlang API in bulk to limit issues. There shouldn't be many changes from now on as the API is stabilising. Should we merge this now to fix the build?

**Comment by hadley** [comment]
I think we should merge for now.

**Comment by krlmlr** [comment]
We could ask `Remotes: hadley/rlang@abcdef01`, this should work via devtools. If rlang API updates are irregular, we could perhaps pin rlang in dplyr just before you start working on the API, and release the pin in the PR that makes dplyr compatible to the API again. Would that work?

**Pull request merged**
