### PR TITLE
add 'frame_data() (#804)

### PR DESCRIPTION
**Pull request by kevinushey**
This PR implements the proposed

```R
frame_data(
    ~colA, ~colB,
    "a", 1,
    "b", 2
)
```

as a means of constructing `data_frame`. `tibble` is also included as an alias, because it's too awesome a name not to use.

### CODE REVIEW

**Comment by hadley** [comment]
Nice! Could you please add a bullet to NEWS?

**Comment by kevinushey** [comment]
Just as you posted ;)

**Comment by hadley** [comment]
Thanks!

**Comment by krlmlr** [comment]
Constructing tables with more than two rows doesn't work for me (1405946245d65c32b):

```r
tbl <- dplyr::tibble(
  ~a, ~b,
  "1", 1,
  "1", 2,
  "2", 1)

tbl
```

```
## Source: local data frame [2 x 2]
## 
##       a     b
##   (chr) (chr)
## 1     1     1
## 2     2     2
```

```r
tbl <- dplyr::tibble(
  ~a, ~b,
  "1", 1,
  "1", 2,
  "2", 2,
  "2", 1)

tbl
```

```
## Source: local data frame [2 x 2]
## 
##       a     b
##   (chr) (dbl)
## 1     1     1
## 2     2     2
```

```r
tbl <- dplyr::tibble(
  ~a, ~b, ~Freq,
  1, 1, 5,
  1, 2, 6,
  2, 2, 7,
  2, 1, 8)

tbl
```

```
## Source: local data frame [3 x 3]
## 
##       a     b  Freq
##   (dbl) (dbl) (dbl)
## 1     1     1     5
## 2     2     6     2
## 3     7     2     1
```

**Comment by kevinushey** [comment]
Thanks @krlmlr -- I have a PR up that should fix this. https://github.com/hadley/dplyr/pull/1377

Hopefully we can get this in before the `dplyr` submission...

**Comment by klmr** [comment]
This needs better documentation. I’ve just read the above examples and the code and I still had no idea what this function actually does. Only once I read the fix in #1377 did it click.

**Pull request merged**
