### PR TITLE
WIP: A more consistent way to specify query arguments

### PR DESCRIPTION
**Pull request by krlmlr**
This defines a class `qspec` with subclasses that provide more control for programmatic use of dplyr verbs. Currently, an example implementation for `select()` is provided. Each verb (or class of verbs) would get its own `qspec` subclass. This solves two problems:

1. Allows passing raw column names or column indexes to `select_()`
2. Simplifies the definition of a consistent API across backends

## Raw column names

Currently, the user can

- use NSE and pass unquoted column names, column indexes, column ranges, selection predicates, etc. in `...`
- use SE and pass quoted column names, quoted column indexes etc. in `...`
- use SE, construct a `lazy_dots` object and pass it to `.dots`

With `qspec` and its `as.qspec_select.character()` and `as.qspec_select.integer()` methods, the user now can also pass named character or integer vectors. (Before, passing character vectors resulted in a call to `parse()`, so that non-syntactic names could not be used directly.)

Passing character vectors also circumvents encoding problems.

The implementation currently addresses #2243 for the `select_if()` case:

```r
> data_frame("a b c" = 1) %>% select_if(TRUE)
  `a b c`
    <dbl>
1       1
```

## Consistent API

For each backend, the implementation of `select_()` basically has to do the same steps:

- call `as.lazy_dots()`
- call `select_vars_()`
- in the grouped case, call `ensure_grouped_vars()`

With `qspec` it is sufficient to call `as.qspec_select()`, and the implementation will figure out what to do, independent of the backend and of the current grouping. This also simplifies future changes/enhancements to the argument processing.

## TODO

- Implement `qspec` for all other verbs
- Use a better name than `qspec`.

@hadley: PTAL.

### CODE REVIEW

**Comment by krlmlr** [comment]
@lionel-: Hadley suggests that most of this will be covered by rlang/tidyeval. Would you like to comment?

**Comment by lionel-** [comment]
yes, rlang will feature tidy evaluation which makes it possible and easy to program with any NSE functions. We are even considering dropping the idiom of pairing NSE functions with a SE version.

You'll be able to do:

```r
column <- ~cyl
select(mtcars, !! column)
```

or:

```r
var <- 10
dots <- list(
  cyl = ~ 2 * cyl,
  new = ~ disp + var
)

mutate(mtcars, !!! dots)
```

Wrapping around a NSE function will be handled like this:

```r
wrapper <- function(df, ...) {
  mutate(df, !!! tidy_dots(...))
}
```

`!!` is a shortcut for unquoting and `!!!` for unquote-splicing. The whole thing works because the evaluation environment treats formulas as self-evaluating promises. See https://github.com/hadley/rlang/pull/19

**Comment by krlmlr** [comment]
Thanks. I still feel that we need something like this PR, but probably after converting dplyr to use tidyeval. Are you planning to implement this any time soon?

**Comment by lionel-** [comment]
I'm not sure it would still be needed. E.g. you can have all of:

```r
var1 <- ~3

foo <- "d"
var2 <- tidy_quote(starts_with(!! foo))

var3 <- ~drat

select(mtcars, !!var1, !!var2, !!var3)
```

Also the `:=` operator will make it possible to have programmable dots names. E.g.:

```r
new_col <- "foo"
select(mtcars, new_col := cyl, toupper(new_col) := drat)
```

We should be able to start porting the tidyverse to tidyeval sometime this month, hopefully next week.

**Comment by krlmlr** [comment]
Can you give an example of how the new implementation of `mutate_if()` would look like?

**Comment by lionel-** [comment]
probably something like:

```r
select_if <- function(.data, .predicate, ...) {
  if (inherits(.data, "tbl_lazy")) {
    stop("Selection with predicate currently require local sources",
      call. = FALSE)
  }
  vars <- probe_colwise_names(.data, .predicate, ...)
  vars <- ensure_grouped_vars(vars, .data, notify = FALSE)

  vars <- lapply(vars, as.name)
  select(.data, !!! vars)
}
```

**Comment by krlmlr** [comment]
Using `as.name()` will give us encoding headaches on Windows (#1950). Is there a way without converting to language symbols?

**Comment by lionel-** [comment]
We could convert the names to column positions.

**Comment by krlmlr** [comment]
I'm not convinced yet. To me, it looks like the new tools are great for interactive use, but I feel that for programming an extra layer like I'm suggesting is helpful. Let's discuss this again after converting dplyr to tidyeval.

**Pull request closed without merging**
